jobs:
  - job: BuildPublishProject
    displayName: Build and publish the project artifact
    steps:
      - checkout: self
        fetchDepth: 1
        clean: true

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
          architecture: "x64"

      - bash: |
          pip install --upgrade pip
          pip install --target="./.python_packages/lib/site-packages" -r ./requirements.txt
        workingDirectory: "$(Build.SourcesDirectory)"
        displayName: Install Python packages

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(Build.SourcesDirectory)"
          includeRootFolder: false
          archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
          artifactName: "drop"