jobs:
  - job: ValidateBicepCode
    displayName: Validate Bicep code configurations
    dependsOn:
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        name: PreflightValidation
        inputs:
          serviceConnection: ${{parameters.serviceConnection}}
          deploymentMode: Validation
          resourceGroupName: ${{parameters.resourceGroupName}}
          csmFile: ${{parameters.resourceFile}}
          csmParametersFile: ${{parameters.paramtersFile}}
          location: ${{parameters.location}}